/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    HgCode: typeof import('./../src/components/HgCode.vue')['default']
    ReturnPageBtn: typeof import('./../src/components/ReturnPageBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Signin: typeof import('./../src/components/auth/signin.vue')['default']
    Signup: typeof import('./../src/components/auth/signup.vue')['default']
    SvgPlugin: typeof import('./../src/components/SvgPlugin.vue')['default']
  }
}
